name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    strategy:
      matrix:
        include:
          - prefix: stable-win-x64
            os: windows-latest
          - prefix: stable-linux-x64
            os: ubuntu-22.04
          - prefix: stable-macos-x64
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build:stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wow-export-${{ matrix.prefix }}
          path: artifacts/*
          retention-days: 7
